name: Setup GPG Secrets
description: A custom GitHub action to set up GPG secrets for Maven
inputs:
  MAVEN_SETTINGS_XML:
    description: 'custom settings.xml'
    required: true
  GPG_PASSPHRASE:
    description: 'GPG passphrase'
    required: true
  GPG_KEY_BASE64:
    description: 'Base64 encoded GPG key'
    required: true
runs:
  using: 'composite'  
  steps:
    - name: Make secrets directory
      run: |
       mkdir -p /home/runner/work/secrets
       printf "%s" "${{ inputs.MAVEN_SETTINGS_XML }}" > /home/runner/work/secrets/settings.xml
       printf "%s" "${{ inputs.GPG_PASSPHRASE }}" > /home/runner/work/secrets/passphrase.file
       echo "${{ inputs.GPG_KEY_BASE64 }}" | base64 --decode > /home/runner/work/secrets/galasa.gpg
       mkdir -p /home/runner/work/gpg
       chmod 700 /home/runner/work/gpg
       gpg --homedir /home/runner/work/gpg --pinentry-mode loopback --passphrase-file /home/runner/work/secrets/passphrase.file --import /home/runner/work/secrets/galasa.gpg
       cp /home/runner/work/secrets/settings.xml /home/runner/work/gpg/settings.xml
      shell: bash